# Generated by Django 5.2 on 2025-05-22 06:47

import autoslug.fields
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='service_title', unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_des',
            field=tinymce.models.HTMLField(),
        ),
    ]
